web:
  service:
    type: LoadBalancer
    port: 8088
    annotations: {
      external-dns.alpha.kubernetes.io/hostname: "temporal.lofianimated.com"
    }
  
server:
  frontend:
    service:
      annotations: {external-dns.alpha.kubernetes.io/hostname: frontend.lofianimated.com}
      type: LoadBalancer
      port: 7233
    metrics:
      enabled: false
      serviceMonitor: {}
      prometheus: {}
    podAnnotations: {}
    resources: {}
    nodeSelector: {}
    tolerations: []
    affinity: {}

  config:
    persistence:
      default:
        driver: "sql"

        sql:
          driver: "postgres"
          host: host
          port: 25060
          database: temporal
          user: temporal_dev
          password: pass
          maxConns: 5
          maxConnLifetime: "1h"
          tls:
            enabled: true

      visibility:
        driver: "sql"

        sql:
          driver: "postgres"
          host: host
          port: 25060
          database: temporal_visibility
          user: temporal_dev
          password: pass
          maxConns: 5
          maxConnLifetime: "1h"
          tls:
            enabled: true
grafana:
  enabled: false

elasticsearch:
  enabled: false

prometheus:
  enabled: false

kafka:
  enabled: false

cassandra:
  enabled: false

mysql:
  enabled: false

postgresql:
  enabled: false

schema:
  setup:
    enabled: false
    
  update:
    enabled: false
