server:
  frontend:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi

  history:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi

  matching:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi

  worker:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
